"""
Django settings for blog_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Render 환경 변수가 있으면 사용하고, 없으면 로컬용 기본 키를 사용합니다.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-t!mlp5e-b@)37_#ij3t60)92z*_+yzekmhn#!vyfszvfnc5e6e')

# SECURITY WARNING: don't run with debug turned on in production!
# Render 배포 서버 환경('RENDER' 환경 변수 존재)에서는 자동으로 False가 됩니다.
DEBUG = 'RENDER' not in os.environ

# 로컬 개발 환경 호스트 등록
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 서드파티 및 커스텀 앱들
    'rest_framework',
    'corsheaders',
    'posts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                     # CORS 미들웨어 (최상단 유지)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",               # ⭐️ 정적 파일 배포를 위한 WhiteNoise 추가
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blog_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ⭐️ Render 호스팅 환경일 경우 PostgreSQL 데이터베이스로 전환합니다.
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# ⭐️ 배포 환경용 정적 파일 모음 경로 설정 (WhiteNoise 연동)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS 설정 (React 개발 서버와 통신용)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite 개발 서버
    "http://localhost:3000",   # 대체 포트
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "https://songhaparkpharm.uk",       # 내 도메인 추가 (www 없는 버전)
    "https://www.songhaparkpharm.uk",
]


# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 한 페이지에 10개씩
}


#  Render 배포 환경에서의 호스트 도메인 자동 허용 및 확장 설정
if os.environ.get('RENDER_EXTERNAL_URL'):
    RENDER_EXTERNAL_URL = os.environ.get('RENDER_EXTERNAL_URL')
    
    # 배포된 장고 백엔드 서버 자체의 도메인을 ALLOWED_HOSTS에 추가
    backend_domain = RENDER_EXTERNAL_URL.replace('https://', '').replace('http://', '')
    ALLOWED_HOSTS.append(backend_domain)
    
    # 프론트엔드가 배포되면 아래 배포용 CORS 설정 영역에 프론트엔드 도메인을 추가해주면 됩니다.
    # 예시: CORS_ALLOWED_ORIGINS.append("https://your-react-app.onrender.com")


# 업로드된 사진(Media)이 저장되고 서빙되는 경로 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 2. Cloudinary 연동 키 설정
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

# 3. 미디어 파일 저장소로 Cloudinary 지정
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

