"""
Django settings for blog_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-t!mlp5e-b@)37_#ij3t60)92z*_+yzekmhn#!vyfszvfnc5e6e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

# 내 백엔드 도메인
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'blog-backend-35eq.onrender.com'
]


# Application definition

INSTALLED_APPS = [
    # 💥 [롤백] 다언어 확장 패키지 "modeltranslation" 완벽 제거!
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    
    # 클라우디너리는 반드시 staticfiles 바로 위에 이 순서대로!
    "cloudinary_storage",
    "cloudinary",
    
    "django.contrib.staticfiles",
    
    # 서드파티 및 커스텀 앱들
    'rest_framework',
    'corsheaders',
    'posts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                     # CORS 미들웨어 (최상단 유지)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",               # 정적 파일 배포를 위한 WhiteNoise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 💥 [롤백] 다언어 감지 미들웨어(LocaleMiddleware)가 있던 자리를 깔끔하게 정리했습니다.
]

ROOT_URLCONF = "blog_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Render 호스팅 환경일 경우 PostgreSQL 데이터베이스로 전환합니다.
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr" # 깔끔하게 단일 한글 사양으로 명시

TIME_ZONE = "Europe/Vienna" # 비엔나 시간대 유지

USE_I18N = True
USE_TZ = True

# [롤백] 3개 국어를 명시하던 LANGUAGES 변수를 통째로 제거하여 단일 언어로 원상복구했습니다.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# 배포 환경용 정적 파일 모음 경로 설정 (WhiteNoise 연동)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS 설정 (React 개발 서버와 통신용)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite 개발 서버
    "http://localhost:3000",   # 대체 포트
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "https://songhaparkpharm.uk",       # 내 도메인
    "https://www.songhaparkpharm.uk",
]


# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    
    # API 요청이 들어왔을 때 JWT 토큰 열쇠를 검사하는 감시관
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# Render 배포 환경에서의 호스트 도메인 자동 허용 및 확장 설정
if os.environ.get('RENDER_EXTERNAL_URL'):
    RENDER_EXTERNAL_URL = os.environ.get('RENDER_EXTERNAL_URL')
    
    backend_domain = RENDER_EXTERNAL_URL.replace('https://', '').replace('http://', '')
    ALLOWED_HOSTS.append(backend_domain)


# 업로드된 사진(Media)이 저장되고 서빙되는 경로 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary 연동 키 설정
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

# 미디어 파일 저장소로 Cloudinary 지정
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# JWT 토큰 관련 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), 
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),            
}