# Generated by Django 5.2.14 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_ko",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ko",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
