# Generated by Django 5.2.14 on 2026-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_content_de_post_content_en_post_content_ko_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content_de",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content_ko",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title_ko",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
